# Generated by Django 4.2 on 2025-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('user_id', models.BigIntegerField(verbose_name='投诉用户ID')),
                ('house_id', models.BigIntegerField(verbose_name='关联的房产ID')),
                ('type', models.CharField(max_length=50, verbose_name='投诉类型')),
                ('title', models.CharField(max_length=255, verbose_name='投诉标题')),
                ('content', models.TextField(verbose_name='投诉详细内容')),
                ('image_urls', models.JSONField(blank=True, null=True, verbose_name='投诉图片URL数组')),
                ('status', models.CharField(choices=[('submitted', '已提交'), ('processing', '处理中'), ('resolved', '已解决'), ('rejected', '已驳回')], default='submitted', max_length=20, verbose_name='状态')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('processor_id', models.BigIntegerField(blank=True, null=True, verbose_name='处理人员ID（物业员工）')),
                ('process_remark', models.TextField(blank=True, null=True, verbose_name='处理备注')),
            ],
            options={
                'verbose_name': '投诉建议',
                'verbose_name_plural': '投诉建议',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_id', models.BigIntegerField(verbose_name='报修用户ID')),
                ('house_id', models.BigIntegerField(verbose_name='房产ID')),
                ('type', models.CharField(max_length=32, verbose_name='报修类型')),
                ('description', models.TextField(verbose_name='问题描述')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='图片URL列表')),
                ('urgency', models.CharField(choices=[('high', '紧急'), ('medium', '一般'), ('low', '低')], default='medium', max_length=20, verbose_name='紧急程度')),
                ('status', models.CharField(choices=[('pending', '待受理'), ('processing', '处理中'), ('completed', '已完成'), ('rejected', '已驳回'), ('waiting_resident', '待居民补充')], default='pending', max_length=20, verbose_name='工单状态')),
                ('assigned_to', models.BigIntegerField(blank=True, null=True, verbose_name='指派给（维修工ID）')),
                ('assigned_at', models.DateTimeField(blank=True, null=True, verbose_name='指派时间')),
                ('expected_finish_at', models.DateTimeField(blank=True, null=True, verbose_name='预计完成时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='实际完成时间')),
                ('warning_time', models.DateTimeField(blank=True, null=True, verbose_name='预警触发时间')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='驳回原因')),
                ('resident_supplement', models.TextField(blank=True, null=True, verbose_name='居民补充信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '工单',
                'verbose_name_plural': '工单',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderComment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('work_order_id', models.BigIntegerField(verbose_name='工单ID')),
                ('user_id', models.BigIntegerField(verbose_name='留言用户ID')),
                ('content', models.TextField(verbose_name='留言内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '工单留言',
                'verbose_name_plural': '工单留言',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderRating',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('work_order_id', models.BigIntegerField(unique=True, verbose_name='工单ID')),
                ('service_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='服务质量（1-5）')),
                ('efficiency_rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], verbose_name='处理效率（1-5）')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='评价内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评价时间')),
            ],
            options={
                'verbose_name': '工单评价',
                'verbose_name_plural': '工单评价',
            },
        ),
    ]
