# Generated by Django 4.2 on 2025-10-31 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='楼栋名称')),
                ('unit_count', models.IntegerField(default=1, verbose_name='单元数')),
            ],
            options={
                'verbose_name': '楼栋',
                'verbose_name_plural': '楼栋',
            },
        ),
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='小区名称')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('property_phone', models.CharField(max_length=20, verbose_name='物业电话')),
                ('fee_standard', models.DecimalField(decimal_places=2, help_text='元/平米', max_digits=10, verbose_name='物业费标准')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '小区',
                'verbose_name_plural': '小区',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('unit', models.CharField(max_length=10, verbose_name='单元号')),
                ('number', models.CharField(max_length=10, verbose_name='房号')),
                ('area', models.DecimalField(decimal_places=2, help_text='平方米', max_digits=8, verbose_name='建筑面积')),
                ('owner_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='业主姓名')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='houses', to='communities.building', verbose_name='楼栋')),
            ],
            options={
                'verbose_name': '房屋',
                'verbose_name_plural': '房屋',
                'unique_together': {('building', 'unit', 'number')},
            },
        ),
        migrations.CreateModel(
            name='VisitorPass',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('user_id', models.BigIntegerField(verbose_name='生成此通行证的居民用户ID')),
                ('house_id', models.BigIntegerField(verbose_name='访问的房产ID')),
                ('visitor_name', models.CharField(max_length=100, verbose_name='访客姓名')),
                ('visitor_phone', models.CharField(max_length=20, verbose_name='访客手机号')),
                ('pass_code', models.CharField(default=uuid.uuid4, max_length=32, verbose_name='唯一的通行二维码内容')),
                ('valid_from', models.DateTimeField(verbose_name='有效期开始时间')),
                ('valid_to', models.DateTimeField(verbose_name='有效期结束时间')),
                ('status', models.CharField(choices=[('active', '有效'), ('used', '已使用'), ('expired', '已过期'), ('cancelled', '已取消')], default='active', max_length=20, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '访客通行证',
                'verbose_name_plural': '访客通行证',
            },
        ),
        migrations.CreateModel(
            name='PropertyFeeBill',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键ID')),
                ('house_id', models.BigIntegerField(verbose_name='关联的房屋ID')),
                ('billing_period', models.CharField(help_text='格式：YYYY-MM', max_length=7, verbose_name='账期')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='应缴金额')),
                ('status', models.CharField(choices=[('pending', '待支付'), ('paid', '已支付'), ('overdue', '已逾期')], default='pending', max_length=20, verbose_name='状态')),
                ('due_date', models.DateField(verbose_name='缴费截止日期')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='支付成功时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='账单创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='最后更新时间')),
            ],
            options={
                'verbose_name': '物业费账单',
                'verbose_name_plural': '物业费账单',
                'unique_together': {('house_id', 'billing_period')},
            },
        ),
        migrations.AddField(
            model_name='building',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='communities.community', verbose_name='小区'),
        ),
        migrations.CreateModel(
            name='UserHouse',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('relationship', models.CharField(choices=[('owner', '业主'), ('family', '家庭成员')], default='owner', max_length=10, verbose_name='关系')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=10, verbose_name='审核状态')),
                ('certificate_image', models.CharField(blank=True, max_length=255, null=True, verbose_name='房产证照片URL')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_houses', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_houses', to='communities.house', verbose_name='房屋')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_houses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户房产绑定',
                'verbose_name_plural': '用户房产绑定',
                'unique_together': {('user', 'house')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='building',
            unique_together={('community', 'name')},
        ),
    ]
