# Generated by Django 4.2 on 2025-11-06 15:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyfeebill',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID'),
        ),
        migrations.AlterField(
            model_name='userhouse',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键'),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键ID'),
        ),
        migrations.AlterField(
            model_name='visitorpass',
            name='pass_code',
            field=models.CharField(default=uuid.uuid4, max_length=64, verbose_name='唯一的通行二维码内容'),
        ),
    ]
