# Generated by Django 4.2 on 2025-10-31 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_id', models.BigIntegerField(verbose_name='接收用户ID')),
                ('title', models.CharField(max_length=200, verbose_name='消息标题')),
                ('notification_type', models.CharField(choices=[('work_order', '工单通知'), ('announcement', '公告通知'), ('merchant_post', '商户动态通知'), ('system', '系统通知')], default='system', max_length=20, verbose_name='消息种类')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('related_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联业务ID')),
                ('is_read', models.BooleanField(default=False, verbose_name='是否已读')),
                ('sent_via', models.CharField(choices=[('app', '应用内'), ('sms', '短信'), ('wechat', '微信')], default='app', max_length=20, verbose_name='发送渠道')),
                ('sent_status', models.CharField(choices=[('pending', '待发送'), ('sent', '已发送'), ('failed', '发送失败')], default='pending', max_length=20, verbose_name='发送状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '消息通知',
                'verbose_name_plural': '消息通知',
                'ordering': ['-created_at'],
            },
        ),
    ]
