# Generated by Django 4.2 on 2025-10-31 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='角色名（admin,客服,维修工）')),
                ('role_type', models.CharField(choices=[('property', '物业'), ('merchant', '商户'), ('resident', '居民')], max_length=20, verbose_name='角色类型')),
                ('permissions', models.JSONField(blank=True, default=dict, null=True, verbose_name='权限列表（菜单+操作）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '角色权限',
                'verbose_name_plural': '角色权限',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('openid', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='微信OpenID')),
                ('username', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='用户名')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='手机号')),
                ('avatar_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像URL')),
                ('role_id', models.IntegerField(blank=True, null=True, verbose_name='角色id')),
                ('is_active', models.BooleanField(default=False, verbose_name='是否激活')),
                ('is_staff', models.BooleanField(default=False, verbose_name='是否是员工')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否是超级用户')),
                ('is_blacklisted', models.BooleanField(default=False, verbose_name='是否黑名单用户')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='是否删除')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'ordering': ['-created_at'],
            },
        ),
    ]
