# Generated by Django 4.2 on 2025-10-31 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100, verbose_name='操作描述')),
                ('resource_type', models.CharField(max_length=50, verbose_name='资源类型')),
                ('resource_id', models.BigIntegerField(blank=True, null=True, verbose_name='资源ID')),
                ('ip_address', models.CharField(max_length=45, verbose_name='IP地址')),
                ('user_agent', models.TextField(verbose_name='用户代理')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MerchantStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='统计日期')),
                ('page_views', models.IntegerField(default=0, verbose_name='页面访问量')),
                ('favorite_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('coupon_views', models.IntegerField(default=0, verbose_name='优惠券查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='merchants.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '商户统计',
                'verbose_name_plural': '商户统计',
                'unique_together': {('merchant', 'date')},
            },
        ),
    ]
