# Generated by Django 4.2 on 2025-10-29 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(help_text='主键ID', primary_key=True, serialize=False)),
                ('order_number', models.CharField(blank=True, help_text='平台内部生成的唯一订单号', max_length=64, null=True, unique=True)),
                ('user_id', models.BigIntegerField(help_text='发起支付的用户ID')),
                ('bill_id', models.BigIntegerField(blank=True, help_text='关联的物业费账单ID（可为空，预留其他支付）', null=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='支付金额', max_digits=10)),
                ('status', models.CharField(choices=[('created', '已创建'), ('paid', '成功'), ('failed', '失败'), ('refunded', '已退款')], default='created', help_text='支付状态', max_length=20)),
                ('payment_gateway', models.CharField(blank=True, choices=[('wechat', '微信支付'), ('alipay', '支付宝')], help_text='支付网关', max_length=50, null=True)),
                ('gateway_order_no', models.CharField(blank=True, help_text='支付平台返回的交易号', max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='订单创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='订单更新时间')),
                ('paid_at', models.DateTimeField(blank=True, help_text='支付成功时间', null=True)),
            ],
            options={
                'verbose_name': '支付订单',
                'verbose_name_plural': '支付订单',
                'db_table': 'payment_orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
