# Generated by Django 4.2 on 2025-10-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_id', models.BigIntegerField(blank=True, null=True, verbose_name='关联用户ID')),
                ('name', models.CharField(max_length=100, verbose_name='商户名称')),
                ('service_categories', models.CharField(blank=True, choices=[('REPAIR_SERVICE', '维修服务'), ('LIFE_SERVICE', '生活服务'), ('RETAIL_STORE', '商超零售'), ('FOOD_BEVERAGE', '餐饮')], max_length=50, null=True, verbose_name='服务分类')),
                ('address', models.CharField(max_length=200, verbose_name='地址')),
                ('phone', models.CharField(max_length=20, verbose_name='联系电话')),
                ('business_hours', models.CharField(max_length=100, verbose_name='营业时间')),
                ('description', models.TextField(verbose_name='服务介绍')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='门店照片URL列表')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='入驻状态')),
                ('approved_by', models.BigIntegerField(blank=True, null=True, verbose_name='审核人ID')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商户',
                'verbose_name_plural': '商户',
            },
        ),
        migrations.CreateModel(
            name='MerchantPost',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('merchant_id', models.BigIntegerField(verbose_name='商户ID')),
                ('title', models.CharField(max_length=200, verbose_name='动态标题')),
                ('content', models.TextField(verbose_name='动态内容')),
                ('images', models.JSONField(blank=True, null=True, verbose_name='图片列表')),
                ('like_count', models.IntegerField(default=0, verbose_name='点赞数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '商户动态',
                'verbose_name_plural': '商户动态',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PostComment',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('post_id', models.BigIntegerField(verbose_name='动态ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
            ],
            options={
                'verbose_name': '动态评论',
                'verbose_name_plural': '动态评论',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('target_type', models.CharField(choices=[('merchant', '商户'), ('coupon', '优惠券')], max_length=20, verbose_name='收藏类型')),
                ('target_id', models.BigIntegerField(verbose_name='收藏目标ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '用户收藏',
                'verbose_name_plural': '用户收藏',
                'unique_together': {('user_id', 'target_type', 'target_id')},
            },
        ),
        migrations.CreateModel(
            name='PostLike',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='主键')),
                ('user_id', models.BigIntegerField(verbose_name='用户ID')),
                ('post_id', models.BigIntegerField(verbose_name='动态ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '动态点赞',
                'verbose_name_plural': '动态点赞',
                'unique_together': {('user_id', 'post_id')},
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='优惠标题')),
                ('description', models.TextField(verbose_name='优惠内容')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='优惠图片')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('end_date', models.DateField(verbose_name='结束日期')),
                ('view_count', models.IntegerField(default=0, verbose_name='查看次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='merchants.merchant', verbose_name='商户')),
            ],
            options={
                'verbose_name': '优惠券',
                'verbose_name_plural': '优惠券',
            },
        ),
    ]
